import prisma from '@/lib/prisma';
import { NextRequest, NextResponse } from 'next/server';
import { parseJSON } from '@/lib/utils';

// GET /api - API Documentation
export async function GET(request: NextRequest) {
  const apiEndpoints = {
    success: true,
    message: 'MS BD API Documentation',
    baseUrl: 'http://localhost:3000/api',
    version: '1.0.0',
    endpoints: [
      {
        id: 1,
        name: 'Comprehensive Data',
        method: 'GET',
        path: '/api/all',
        description: 'Get all website data A to Z (products, teams, orders, contacts, statistics)',
        query: 'None',
        exampleResponse: {
          success: true,
          data: {
            shop: {},
            products: {},
            teams: {},
            orders: {},
            contacts: {},
            statistics: {},
            financials: {},
          },
        },
      },
      {
        id: 2,
        name: 'Shop Information',
        method: 'GET',
        path: '/api/shop',
        description: 'Get shop details (name, email, phone, address, business hours)',
        query: 'None',
        exampleResponse: {
          success: true,
          data: {
            name: 'MS BD',
            tagline: 'Your Jersey. Your Team.',
            email: 'hello@msbd.example',
            phone: '+8801000000000',
          },
        },
      },
      {
        id: 3,
        name: 'Get All Products',
        method: 'GET',
        path: '/api/products',
        description: 'Get all products with filtering, sorting, and pagination',
        query: '?category=club&team=real-madrid&search=jersey&minPrice=1000&maxPrice=3000&featured=true&page=1&limit=10&sort=newest',
        exampleResponse: {
          success: true,
          data: [],
          pagination: { page: 1, limit: 10, total: 40, pages: 4 },
        },
      },
      {
        id: 4,
        name: 'Get Product by ID',
        method: 'GET',
        path: '/api/products/:id',
        description: 'Get single product details by ID',
        exampleResponse: {
          success: true,
          data: { id: 1, name: 'Real Madrid Home Jersey', price: 2500 },
        },
      },
      {
        id: 5,
        name: 'Get Product by Slug',
        method: 'GET',
        path: '/api/products/slug/:slug',
        description: 'Get single product by slug',
        example: '/api/products/slug/real-madrid-home-jersey-2024',
      },
      {
        id: 6,
        name: 'Create Product',
        method: 'POST',
        path: '/api/products',
        description: 'Create a new product',
        exampleRequest: {
          name: 'New Jersey',
          slug: 'new-jersey',
          team: 'Team Name',
          category: 'club',
          price: 2500,
          stock: 10,
        },
      },
      {
        id: 7,
        name: 'Update Product',
        method: 'PUT',
        path: '/api/products/:id',
        description: 'Update entire product (PUT requires all fields)',
      },
      {
        id: 8,
        name: 'Partial Update Product',
        method: 'PATCH',
        path: '/api/products/:id',
        description: 'Partially update product (PATCH requires only changed fields)',
      },
      {
        id: 9,
        name: 'Delete Product',
        method: 'DELETE',
        path: '/api/products/:id',
        description: 'Delete a product',
      },
      {
        id: 10,
        name: 'Get All Teams',
        method: 'GET',
        path: '/api/teams',
        description: 'Get all teams',
        query: '?category=club or ?category=national',
      },
      {
        id: 11,
        name: 'Get Team by ID',
        method: 'GET',
        path: '/api/teams/:id',
        description: 'Get single team by ID',
      },
      {
        id: 12,
        name: 'Get Team by Slug',
        method: 'GET',
        path: '/api/teams/slug/:slug',
        description: 'Get team by slug',
        example: '/api/teams/slug/real-madrid',
      },
      {
        id: 13,
        name: 'Get Team Products',
        method: 'GET',
        path: '/api/teams/:slug/products',
        description: 'Get all products for a specific team',
      },
      {
        id: 14,
        name: 'Get All Orders',
        method: 'GET',
        path: '/api/orders',
        description: 'Get all orders',
        query: '?status=pending&email=customer@example.com&page=1&limit=10',
      },
      {
        id: 15,
        name: 'Get Order by ID',
        method: 'GET',
        path: '/api/orders/:id',
        description: 'Get single order details with items',
      },
      {
        id: 16,
        name: 'Create Order',
        method: 'POST',
        path: '/api/orders',
        description: 'Create a new order',
        exampleRequest: {
          customerName: 'John Doe',
          phone: '+8801234567890',
          email: 'john@example.com',
          address: 'Dhaka',
          city: 'Dhaka',
          postalCode: '1000',
          paymentMethod: 'cash',
          items: [
            {
              productId: 1,
              productName: 'Jersey',
              size: 'M',
              quantity: 1,
              price: 2500,
              subtotal: 2500,
            },
          ],
          totalAmount: 2500,
        },
      },
      {
        id: 17,
        name: 'Update Order Status',
        method: 'PATCH',
        path: '/api/orders/:id/status',
        description: 'Update order status',
        exampleRequest: { status: 'shipped' },
        statuses: ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled'],
      },
      {
        id: 18,
        name: 'Get Contact Messages',
        method: 'GET',
        path: '/api/contact',
        description: 'Get all contact messages',
        query: '?status=new&page=1&limit=10',
      },
      {
        id: 19,
        name: 'Create Contact Message',
        method: 'POST',
        path: '/api/contact',
        description: 'Submit a contact form message',
        exampleRequest: {
          name: 'John Doe',
          email: 'john@example.com',
          subject: 'Jersey Inquiry',
          message: 'Do you have this jersey in stock?',
        },
      },
    ],
    notes: {
      authentication: 'Not required for v1.0',
      baseUrl: 'http://localhost:3000',
      contentType: 'application/json',
      httpStatusCodes: {
        200: 'Success',
        201: 'Created',
        400: 'Bad Request',
        404: 'Not Found',
        500: 'Server Error',
      },
      n8nUsage: 'All endpoints return JSON format suitable for n8n HTTP Request nodes',
    },
  };

  return NextResponse.json(apiEndpoints, { status: 200 });
}
